config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "properties#index"
  resources :properties do
    collection do
      get 'search'
    end
  end
  resources :users, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/frequency.rb
class Frequency < ActiveHash::Base
  self.data = [
    { id: 1, name: '毎日使用する' },
    { id: 2, name: '2〜3日に1回使用する' },
    { id: 3, name: '週に１回ほど使用する' },
    { id: 4, name: '月に１回ほど使用する' },
    { id: 5, name: '年に１回ほど使用する' }
  ]

  include ActiveHash::Associations
  has_many :properties
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :frequency

  with_options presence: true do
    validates :image
    validates :name
    validates :info
    validates :storage
  end

  validates :frequency_id, numericality: { message: "can't be blank" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :properties

  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_property, except: [:index, :new, :create, :search]

  def index
    @properties = Property.all
    if user_signed_in?
      @properties = Property.where(user_id: current_user.id).order('created_at DESC')
    end
  end

  def new
    @property = Property.new
  end

  def create
    @property = Property.new(property_params)
    if @property.valid?
      @property.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @property.update(property_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    redirect_to root_path if @property.destroy
  end

  def search
    if params[:q]&.dig(:name)
      squished_keywords = params[:q][:name].squish
      params[:q][:name_cont_any] = squished_keywords.split(" ")
    end

    if user_signed_in?
      @q = Property.where(user_id: current_user.id).ransack(params[:q])
    end
    @properties = @q.result
  end

  private

  def property_params
    params.require(:property).permit(:name, :info, :frequency_id, :storage, :image).merge(user_id: current_user.id)
  end

  def set_property
    @property = Property.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MonologApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/edit.html.erb
<div class="properties-register-contents">
<%= render "shared/second-header" %>
  <div class="properties-register-main">
    <h2 class="properties-register-title">
     家の物の情報を編集する
    </h2>
    <%= form_with model: @property, method: :patch, id: 'new_property', local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="img-upload">
     <div class="bold-text">
       家の物の画像
       <span class="essential">必須</span>
      </div>
      <div id="previews"></div>
      <div class="click-upload">
      <p>
        クリックしてファイルをアップロード
      </p>
      <%= f.file_field :image, id:"property-image" %>
    </div>
    <div class="new-properties">
      <div class="bold-text">
        家の物の名前
        <span class="essential">必須</span>
      </div>
      <%= f.text_area :name, class:"properties-text", id:"property-name", placeholder:"家の物の名前（ 40文字まで)", maxlength:"40" %>
      <div class="properties-explain">
        <div class="bold-text">
          家の物の説明
          <span class="essential">必須</span>
        </div>
        <%= f.text_area :info, class:"properties-text", id:"property-info", placeholder:"家の物の説明 （ 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
      </div>
      <div class="form">
        <div class="bold-text">
          使用頻度
          <span class="essential">必須</span>
        </div>
        <%= f.collection_select(:frequency_id, Frequency.all, :id, :name, {include_blank: '---'}, {class:"select-box", id:"property-frequency"}) %>
      </div>
      <div class="properties-place">
        <div class="bold-text">
          保管場所
          <span class="essential">必須</span>
        </div>
        <%= f.text_area :storage, class:"properties-text", id:"property-storage", placeholder:"家の物の保管場所（ 40文字まで)", maxlength:"40" %>
      </div>
    </div>
    <div class="register-btn-contents">
        <%= f.submit "変更する" ,class:"register-btn" %>
        <%=link_to 'もどる', property_path, class:"back-btn" %>
    </div>
    <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/properties/index.html.erb
<%= render "shared/header" %>
<div class="main">

  <div class="title-contents">
    <h2 class="service-title">
      MonoLog
    </h2>
    <p class='service-explain'>
      家の忘れそうな物を登録して
    </p>
    <p class='service-explain'>
      管理できるアプリです
    </p>
  </div>

  <div class="property-contents">
    <h2 class="title">家にある物一覧</h2>
    <ul class="property-lists">
      <% if user_signed_in? %>
        <% @properties.each do |property| %>
          <li class="list">
            <%= link_to property_path(property.id) do %>
              <div class="property-img-content">
                <%= image_tag property.image %><br>
              </div>
              <div class="property-info">
                <h3 class="property-name">
                  <%= property.name %>
                </h3>
                <div class="property-storage">
                  <%= property.storage %>
                </div>
              </div>
            <% end %>
          </li>
        <% end %>
      <% end %>
      <% if user_signed_in? %>
        <% if @properties.length == 0 %>
          <li class='list'>
            <%= image_tag "property-sample.png", class: "property-img" %>
            <div class="property-info">
              <h3 class="property-name">
                物を登録してください
              </h3>
              <div class="property-storage">
                洗面台
              </div>
            </div>
          </li>
        <% end %>
      <% else %>
        <li class='list'>
          <%= image_tag "property-sample.png", class: "property-img" %>
          <div class="property-info">
            <h3 class="property-name">
              ものを登録してください
            </h3>
            <div class="property-storage">
              洗面台
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<%= render "shared/footer" %>

app/views/properties/new.html.erb
<div class="properties-register-contents">
<%= render "shared/second-header" %>
  <div class="properties-register-main">
    <h2 class="properties-register-title">
     家の物の情報を登録する
    </h2>
    <%= form_with model: @property, method: :post, id: 'new_property', local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="img-upload">
     <div class="bold-text">
       家の物の画像
       <span class="essential">必須</span>
      </div>
      <div id="previews"></div>
      <div class="click-upload">
      <p>
        クリックしてファイルをアップロード
      </p>
      <%= f.file_field :image, id:"property-image" %>
    </div>
    <div class="new-properties">
      <div class="bold-text">
        家の物の名前
        <span class="essential">必須</span>
      </div>
      <%= f.text_area :name, class:"properties-text", id:"property-name", placeholder:"家の物の名前（ 40文字まで)", maxlength:"40" %>
      <div class="properties-explain">
        <div class="bold-text">
          家の物の説明
          <span class="essential">必須</span>
        </div>
        <%= f.text_area :info, class:"properties-text", id:"property-info", placeholder:"家の物の説明 （ 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
      </div>
      <div class="form">
        <div class="bold-text">
          使用頻度
          <span class="essential">必須</span>
        </div>
        <%= f.collection_select(:frequency_id, Frequency.all, :id, :name, {include_blank: '---'}, {class:"select-box", id:"property-frequency"}) %>
      </div>
      <div class="properties-place">
        <div class="bold-text">
          保管場所
          <span class="essential">必須</span>
        </div>
        <%= f.text_area :storage, class:"properties-text", id:"property-storage", placeholder:"家の物の保管場所（ 40文字まで)", maxlength:"40" %>
      </div>
    </div>
    <div class="register-btn-contents">
      <%= f.submit "登録する" ,class:"register-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/properties/search.html.erb
<%= render "shared/header" %>
<h3 class="property-search-title">検索ページ</h3>
<h3 class="property-search-subtitle"><%= link_to 'トップページへ戻る', root_path %></h3>
<div class='property-search-contents' id="detailed-search-result-wrapper">
  <%= search_form_for @q, url: search_properties_path, html: {id: "detailed-search-form"} do |f| %>
     <div class="search-field">
      <%= f.label :name, '物の名前' %>
      <br>
      <%= f.text_field :name, placeholder: '物の名前', value: params[:q]&.dig(:name) %>
    </div>
    <div class="search-field">
      <%= f.label :frequency_id_eq, '使用頻度' %>
      <br>
      <%= f.collection_check_boxes(:frequency_id_in, Frequency.all, :id, :name, {include_blank: "---"}) %>
    </div>
    <%= f.submit '検索' %>
  <% end %>
  <ul class='property-search-lists' id="detailed-search-result">
    <% @properties.each do |property| %>
      <li class='list'>
        <div class="posted-content">
          <%= image_tag property.image %><br>
          <%= property.name %><br>
          <%= link_to '詳細', property_path(property.id) %>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/properties/show.html.erb
<%= render "shared/header" %>

<div class="property-show">
  <div class="property-box">
    <h2 class="name">
      <%= @property.name %>
    </h2>
    <div class="property-img-content">
      <%= image_tag @property.image, class: "main-image" %><br>
    </div>
    <div class="property-storage-box">
      <span class="property-storage">
        <%= @property.storage %>
      </span>
    </div>

    <%= link_to "物の編集", edit_property_path, method: :get, class: "property-red-btn" %>
    <p class="or-text">or</p>
    <%= link_to "削除", property_path(@property.id), method: :delete, class:"property-destroy" %>

    <div class="property-explain-box">
      <span><%= @property.info %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-property">所有者</th>
          <td class="detail-value"><%= @property.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-property">使用頻度</th>
          <td class="detail-value"><%= @property.frequency.name %></td>
        </tr>
        <tr>
          <th class="detail-property">保管場所</th>
          <td class="detail-value"><%= @property.storage %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
      <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-contents">
  <p class="footer-text">© All rights reserved by MonoLog.</p>
</div>

app/views/shared/_header.html.erb
<header class="top-page-header">
  <div class='search-bar-contents'>
     <%= search_form_for Property.ransack(params[:q]), url: search_properties_path, html: {class: "search-form"} do |f| %>
      <%= f.text_field :name, placeholder: '物の名前から探す', class: 'input-box' %>
      <br>
      <%= f.label :submit, class: "search-button" do %>
        <%= image_tag "search.png", class:"search-icon" %>
        <%= f.submit :submit, id: "q_submit", style: "display: none;"%>
      <% end %>
    <% end %>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to '物を検索する', search_properties_path, class: "search-register" %></li>
      <li><%= link_to '物を登録する', new_property_path, class: "register" %></li>
    </ul>
    <ul class='lists-right'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, edit_user_path(current_user), class: "user-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second-header.html.erb
<header class="second-header">
  <h2 class="second-header-title">
  MonoLog
  </h2>
</header>

app/views/users/edit.html.erb
<div class="main-contents">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">ユーザー編集</h2>

      <%= link_to "トップページに戻る", root_path, class: 'btn'%>

      <%= form_with model: current_user, local: true do |f| %>
        
       <div class="field">
          <%= f.label :nickname, "ユーザー名" %><br />
          <%= f.text_field :nickname, id:"user_name" %>
        </div>

        <div class="field">
          <%= f.label :email, "メールアドレス" %><br />
          <%= f.email_field :email, id:"user_email", autofocus: true, autocomplete: "email" %>
        </div>

        <div class="actions">
          <%= f.submit "更新する", class: :form__btn  %>
        </div>
      <% end %>
    </div>
  </div>
</div>